services:
  api-gateway-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5035:8080"
    networks:
      - ecommerce-network
    volumes:
      - "./ocelot.prod.json:/app/ocelot.json"

  api-gateway-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5036:8080"
    networks:
      - ecommerce-network
    volumes:
      - "./ocelot.prod.json:/app/ocelot.json"

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - "8085:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
