version: '3.8'

services:
  apigateway:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - ecommerce-v2
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
