version: '3.8'

services:
  apigateway:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - productservice
      - orderservice
    deploy:
      replicas: 3

  productservice:
    image: your-product-service-image
    ports:
      - "5001:80"

  orderservice:
    image: your-order-service-image
    ports:
      - "5002:80"
