services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5035:8080"
    networks:
      - ecommerce-network
    volumes:
      - "./ocelot.prod.json:/app/ocelot.json"

networks:
  ecommerce-network:
    external: true
